[package]
name = "ui_iced"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
crossbeam-channel = "0.5"
name = "$crate"
version = "0.1.0"
edition = "2021"
