[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
notify = "8"
notify-debouncer-mini = "0.6"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
