[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
yaml-front-matter = { workspace = true }
notify = { workspace = true }
anyhow = { workspace = true }
core = { path = "../core" }
