name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install sccache
        run: cargo install sccache --locked
      - name: Enable sccache cache
        run: echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
      - name: Build GUI
        run: cargo build --release -p ui_iced
      - name: Build TUI
        run: cargo build --release -p tui_editor
      - name: Run tests
        run: cargo test --workspace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notes2-${{ matrix.os }}
          path: |
            target/release/ui_iced*
            target/release/tui_editor*

